### PR TITLE
Implementing prompt parameter to authorization endpoint

### PR DESCRIPTION
**Pull request by linuskohl**
Hi,

according to https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.2.1  there is an optional parameter prompt. It provides a workaround to single page applications that cant store refresh tokens. So you can call the authorize endpoint with prompt=none to prevent displaying anything or check if a user is still logged in. More information can be found here: https://auth0.com/docs/api-auth/tutorials/silent-authentication.

Would be happy to get some feedback. Thanks!

### CODE REVIEW

**Comment by linuskohl** [comment]
Hi, just continued with some rework, added tests. Wanted to create a new pull request containing all the updates, pretty much made this one obsolete. Sorry for the inconvenience

**Comment by pgaultier** [comment]
No problem, thank you.

I created a 1.4.0 release to add the MySQL backend

Envoyé de mon mobile

**Comment by linuskohl** [comment]
Hi, I refactored some of the error handling according to https://www.oauth.com/oauth2-servers/authorization/the-authorization-response and https://tools.ietf.org/html/rfc6749#section-4.1.2.1 and added some test cases. Thanks for feedback

**Comment by linuskohl** [comment]
Hi, if everything works it could be merged

**Pull request merged**
